In [3]:
import numpy as np

In [4]:
np.array([1,2,3])

array([1, 2, 3])

In [6]:
b = np.array([[1,2,3],[4,5,6]])

In [7]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
b.shape

(2, 3)

In [11]:
a = np.array([1,2,3])

In [12]:
a.shape

(3,)

In [13]:
b.dtype

dtype('int64')

In [14]:
b.ndim

2

In [15]:
print(type(a))

<class 'numpy.ndarray'>


In [16]:
print(type(b))

<class 'numpy.ndarray'>


In [18]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
c = range(10000)

In [21]:
%timeit [i**3 for i in c]

3.52 ms ± 34.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [22]:
c_numpy = np.arange(10000)

In [23]:
%timeit c_numpy**3

37.4 µs ± 641 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [24]:
l1 = range(10000)

In [25]:
l2 = [i**2 for i in range(10000)]

In [26]:
%timeit list(map(lambda x,y: x*y, l1, l2))

1.39 ms ± 84.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [28]:
a1 = np.array(l1)
b1 = np.array(l2)

In [29]:
%timeit a1*b1

9.81 µs ± 559 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [33]:
np.arange(2,12)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

In [35]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [36]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [37]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
np.full((3,3),2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [39]:
np.full((3,3),2.2)

array([[2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2]])

In [41]:
np.full((3,3),2.2, dtype=np.int)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [43]:
np.diag([1,2,3,4,5,])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [44]:
v = np.array([1,2,3])

In [45]:
v

array([1, 2, 3])

In [46]:
np.tile(v,(3,1))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [47]:
np.tile(v,(3,2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [49]:
np.random.random()

0.23226733943289712

In [50]:
50*np.random.random() + 2

50.135086657993305

In [52]:
np.random.random((3,3))

array([[0.26910564, 0.94268756, 0.67247944],
       [0.32950435, 0.11903778, 0.86766139],
       [0.17236753, 0.76208193, 0.89166329]])

In [53]:
a = np.linspace(1,50,100)

In [54]:
a

array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

In [55]:
a.itemsize

8

In [57]:
b = np.arange(18).reshape(2,3,3)

In [58]:
b.shape

(2, 3, 3)

In [62]:
np.arange(18).reshape(2,3,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [63]:
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [64]:
a = np.array([2,4,6,8,10,12,14,16,18])

In [65]:
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [66]:
a[0]

2

In [67]:
a[2]

6

In [68]:
a[[2,4,6]]

array([ 6, 10, 14])

In [69]:
a[2:]

array([ 6,  8, 10, 12, 14, 16, 18])

In [70]:
a[2:5]

array([ 6,  8, 10])

In [71]:
a[0::2]

array([ 2,  6, 10, 14, 18])

In [72]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [73]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
a[2,2]

9

In [75]:
a > 2

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [76]:
a[(a > 2) & (a<5)]

array([3, 4])

In [77]:
a = np.arange(10)

In [78]:
b = a

In [79]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
b[0] = 11

In [81]:
b

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [82]:
a

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [83]:
np.shares_memory(a,b)

True

In [84]:
a = np.arange(10)

In [87]:
b = a.copy()

In [88]:
b[0] = 11

In [89]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
b

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [91]:
np.shares_memory(a,b)

False

In [92]:
a = np.array([[1,2,3],[4,5,6]])

In [94]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [95]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [96]:
b = np.array([[7,8,9],[10,11,12]])

In [97]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [98]:
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [99]:
a == b

array([[False, False, False],
       [False, False, False]])

In [100]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [101]:
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [102]:
a = np.arange(1,10)

In [103]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [104]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [105]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
       -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [106]:
np.exp(a)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [107]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
np.sum(a)

45

In [109]:
np.median(a)

5.0

In [110]:
a.std()

2.581988897471611

In [115]:
a = np.arange(1,10).reshape(3,3)

In [116]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [117]:
np.linalg.det(a)

0.0

In [121]:
np.linalg.inv(a)

LinAlgError: Singular matrix

In [122]:
np.linalg.eig(a)

(array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [123]:
b = a.T

In [124]:
b

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [125]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [126]:
np.dot(a,b)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [127]:
a = np.array([1,1,0],dtype=bool)

In [128]:
a

array([ True,  True, False])

In [129]:
b = np.array([1,0,1],dtype=bool)

In [130]:
b

array([ True, False,  True])

In [131]:
np.logical_or(a,b)

array([ True,  True,  True])

In [132]:
np.logical_and(a,b)

array([ True, False, False])

In [133]:
a == a

array([ True,  True,  True])

In [134]:
np.all(a==a)

True

In [135]:
np.all(a==b)

False

In [137]:
a = np.array([[1,2],[3,4]])

In [138]:
a

array([[1, 2],
       [3, 4]])

In [139]:
a.sum()

10

In [140]:
a.sum(axis = 0)

array([4, 6])

In [142]:
a.sum(axis = 1)

array([3, 7])

In [143]:
a.max()

4

In [144]:
a.argmax()

3

In [145]:
a

array([[1, 2],
       [3, 4]])

In [146]:
a.shape

(2, 2)

In [147]:
a = np.arange(10)

In [148]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [149]:
a.shape

(10,)

In [150]:
a = np.arange(1,10)

In [151]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [152]:
a[:,np.newaxis].shape

(9, 1)

In [153]:
np.sort(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])